// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: lit-autopilot.proto

package litrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAutopilotSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A human readable label to assign to the session.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// The unix timestamp at which this session should be revoked.
	ExpiryTimestampSeconds uint64 `protobuf:"varint,2,opt,name=expiry_timestamp_seconds,json=expiryTimestampSeconds,proto3" json:"expiry_timestamp_seconds,omitempty"`
	// The address of the mailbox server to connect to for this session.
	MailboxServerAddr string `protobuf:"bytes,3,opt,name=mailbox_server_addr,json=mailboxServerAddr,proto3" json:"mailbox_server_addr,omitempty"`
	// Set to true if tls should be skipped for when connecting to the mailbox.
	DevServer bool `protobuf:"varint,4,opt,name=dev_server,json=devServer,proto3" json:"dev_server,omitempty"`
	// The features that the session should subscribe to. Each feature maps to
	// a FeatureConfig that should be applied to that feature.
	Features map[string]*FeatureConfig `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Rules that apply to the entire session. By default, no rules will apply
	// to the entire session.
	SessionRules *RulesMap `protobuf:"bytes,6,opt,name=session_rules,json=sessionRules,proto3" json:"session_rules,omitempty"`
	// Set to true of the session should not make use of the privacy mapper.
	NoPrivacyMapper bool `protobuf:"varint,7,opt,name=no_privacy_mapper,json=noPrivacyMapper,proto3" json:"no_privacy_mapper,omitempty"`
	// Set to the ID of the group to link this session to, if any.
	LinkedGroupId []byte `protobuf:"bytes,8,opt,name=linked_group_id,json=linkedGroupId,proto3" json:"linked_group_id,omitempty"`
	// The privacy flags used by this session. If set, then privacy_flags_set must
	// be set.
	PrivacyFlags uint64 `protobuf:"varint,9,opt,name=privacy_flags,json=privacyFlags,proto3" json:"privacy_flags,omitempty"`
	// Indicates whether privacy flags are set.
	PrivacyFlagsSet bool `protobuf:"varint,10,opt,name=privacy_flags_set,json=privacyFlagsSet,proto3" json:"privacy_flags_set,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddAutopilotSessionRequest) Reset() {
	*x = AddAutopilotSessionRequest{}
	mi := &file_lit_autopilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAutopilotSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAutopilotSessionRequest) ProtoMessage() {}

func (x *AddAutopilotSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAutopilotSessionRequest.ProtoReflect.Descriptor instead.
func (*AddAutopilotSessionRequest) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{0}
}

func (x *AddAutopilotSessionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AddAutopilotSessionRequest) GetExpiryTimestampSeconds() uint64 {
	if x != nil {
		return x.ExpiryTimestampSeconds
	}
	return 0
}

func (x *AddAutopilotSessionRequest) GetMailboxServerAddr() string {
	if x != nil {
		return x.MailboxServerAddr
	}
	return ""
}

func (x *AddAutopilotSessionRequest) GetDevServer() bool {
	if x != nil {
		return x.DevServer
	}
	return false
}

func (x *AddAutopilotSessionRequest) GetFeatures() map[string]*FeatureConfig {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *AddAutopilotSessionRequest) GetSessionRules() *RulesMap {
	if x != nil {
		return x.SessionRules
	}
	return nil
}

func (x *AddAutopilotSessionRequest) GetNoPrivacyMapper() bool {
	if x != nil {
		return x.NoPrivacyMapper
	}
	return false
}

func (x *AddAutopilotSessionRequest) GetLinkedGroupId() []byte {
	if x != nil {
		return x.LinkedGroupId
	}
	return nil
}

func (x *AddAutopilotSessionRequest) GetPrivacyFlags() uint64 {
	if x != nil {
		return x.PrivacyFlags
	}
	return 0
}

func (x *AddAutopilotSessionRequest) GetPrivacyFlagsSet() bool {
	if x != nil {
		return x.PrivacyFlagsSet
	}
	return false
}

type FeatureConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The RulesMap acts as an override map. In other words, by default the rules
	// values recommended by the Auto Pilot server will be used but the RulesMap
	// can be used to override the defaults.
	Rules *RulesMap `protobuf:"bytes,1,opt,name=rules,proto3" json:"rules,omitempty"`
	// Serialised configuration for the feature.
	Config        []byte `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureConfig) Reset() {
	*x = FeatureConfig{}
	mi := &file_lit_autopilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureConfig) ProtoMessage() {}

func (x *FeatureConfig) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureConfig.ProtoReflect.Descriptor instead.
func (*FeatureConfig) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{1}
}

func (x *FeatureConfig) GetRules() *RulesMap {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *FeatureConfig) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type ListAutopilotSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAutopilotSessionsRequest) Reset() {
	*x = ListAutopilotSessionsRequest{}
	mi := &file_lit_autopilot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAutopilotSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAutopilotSessionsRequest) ProtoMessage() {}

func (x *ListAutopilotSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAutopilotSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListAutopilotSessionsRequest) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{2}
}

type ListAutopilotSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of the Autopilot sessions.
	Sessions      []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAutopilotSessionsResponse) Reset() {
	*x = ListAutopilotSessionsResponse{}
	mi := &file_lit_autopilot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAutopilotSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAutopilotSessionsResponse) ProtoMessage() {}

func (x *ListAutopilotSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAutopilotSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListAutopilotSessionsResponse) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{3}
}

func (x *ListAutopilotSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type AddAutopilotSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Details of the session that was just created.
	Session       *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAutopilotSessionResponse) Reset() {
	*x = AddAutopilotSessionResponse{}
	mi := &file_lit_autopilot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAutopilotSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAutopilotSessionResponse) ProtoMessage() {}

func (x *AddAutopilotSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAutopilotSessionResponse.ProtoReflect.Descriptor instead.
func (*AddAutopilotSessionResponse) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{4}
}

func (x *AddAutopilotSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListAutopilotFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAutopilotFeaturesRequest) Reset() {
	*x = ListAutopilotFeaturesRequest{}
	mi := &file_lit_autopilot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAutopilotFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAutopilotFeaturesRequest) ProtoMessage() {}

func (x *ListAutopilotFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAutopilotFeaturesRequest.ProtoReflect.Descriptor instead.
func (*ListAutopilotFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{5}
}

type ListAutopilotFeaturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map of feature names to Feature objects describing the feature.
	Features      map[string]*Feature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAutopilotFeaturesResponse) Reset() {
	*x = ListAutopilotFeaturesResponse{}
	mi := &file_lit_autopilot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAutopilotFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAutopilotFeaturesResponse) ProtoMessage() {}

func (x *ListAutopilotFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAutopilotFeaturesResponse.ProtoReflect.Descriptor instead.
func (*ListAutopilotFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{6}
}

func (x *ListAutopilotFeaturesResponse) GetFeatures() map[string]*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

type RevokeAutopilotSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The local static public key of the Autopilot session to be revoked.
	// When using REST, this field must be encoded as base64url.
	LocalPublicKey []byte `protobuf:"bytes,1,opt,name=local_public_key,json=localPublicKey,proto3" json:"local_public_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RevokeAutopilotSessionRequest) Reset() {
	*x = RevokeAutopilotSessionRequest{}
	mi := &file_lit_autopilot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAutopilotSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAutopilotSessionRequest) ProtoMessage() {}

func (x *RevokeAutopilotSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAutopilotSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeAutopilotSessionRequest) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeAutopilotSessionRequest) GetLocalPublicKey() []byte {
	if x != nil {
		return x.LocalPublicKey
	}
	return nil
}

type RevokeAutopilotSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeAutopilotSessionResponse) Reset() {
	*x = RevokeAutopilotSessionResponse{}
	mi := &file_lit_autopilot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeAutopilotSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeAutopilotSessionResponse) ProtoMessage() {}

func (x *RevokeAutopilotSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeAutopilotSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeAutopilotSessionResponse) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{8}
}

type Feature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the name of the Autopilot feature.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A human readable description of what the feature offers.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// A map of rules that make sense for this feature. Each rule is accompanied
	// with appropriate default values for the feature along with minimum and
	// maximum values for the rules.
	Rules map[string]*RuleValues `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A list of URI permissions required by the feature.
	PermissionsList []*Permissions `protobuf:"bytes,4,rep,name=permissions_list,json=permissionsList,proto3" json:"permissions_list,omitempty"`
	// A boolean indicating if the user would need to upgrade their Litd version in
	// order to subscribe to the Autopilot feature. This will be true if the
	// feature rules set contains a rule that Litd is unaware of.
	RequiresUpgrade bool `protobuf:"varint,5,opt,name=requires_upgrade,json=requiresUpgrade,proto3" json:"requires_upgrade,omitempty"`
	// The JSON-marshaled representation of a feature's default configuration.
	DefaultConfig string `protobuf:"bytes,6,opt,name=default_config,json=defaultConfig,proto3" json:"default_config,omitempty"`
	// This feature may require relaxed privacy obfuscation that can be enabled
	// with these flags.
	PrivacyFlags  uint64 `protobuf:"varint,7,opt,name=privacy_flags,json=privacyFlags,proto3" json:"privacy_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_lit_autopilot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{9}
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feature) GetRules() map[string]*RuleValues {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Feature) GetPermissionsList() []*Permissions {
	if x != nil {
		return x.PermissionsList
	}
	return nil
}

func (x *Feature) GetRequiresUpgrade() bool {
	if x != nil {
		return x.RequiresUpgrade
	}
	return false
}

func (x *Feature) GetDefaultConfig() string {
	if x != nil {
		return x.DefaultConfig
	}
	return ""
}

func (x *Feature) GetPrivacyFlags() uint64 {
	if x != nil {
		return x.PrivacyFlags
	}
	return 0
}

type RuleValues struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether or not the users version of Litd is aware of this rule.
	Known bool `protobuf:"varint,1,opt,name=known,proto3" json:"known,omitempty"`
	// The default values for the rule that the Autopilot server recommends for
	// the associated feature.
	Defaults *RuleValue `protobuf:"bytes,2,opt,name=defaults,proto3" json:"defaults,omitempty"`
	// The minimum sane value for this rule for the associated feature.
	MinValue *RuleValue `protobuf:"bytes,3,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	// The maximum sane value for this rule for the associated feature.
	MaxValue      *RuleValue `protobuf:"bytes,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleValues) Reset() {
	*x = RuleValues{}
	mi := &file_lit_autopilot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleValues) ProtoMessage() {}

func (x *RuleValues) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleValues.ProtoReflect.Descriptor instead.
func (*RuleValues) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{10}
}

func (x *RuleValues) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *RuleValues) GetDefaults() *RuleValue {
	if x != nil {
		return x.Defaults
	}
	return nil
}

func (x *RuleValues) GetMinValue() *RuleValue {
	if x != nil {
		return x.MinValue
	}
	return nil
}

func (x *RuleValues) GetMaxValue() *RuleValue {
	if x != nil {
		return x.MaxValue
	}
	return nil
}

type Permissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URI in question.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// A list of the permissions required for this method.
	Operations    []*MacaroonPermission `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_lit_autopilot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_lit_autopilot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_lit_autopilot_proto_rawDescGZIP(), []int{11}
}

func (x *Permissions) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Permissions) GetOperations() []*MacaroonPermission {
	if x != nil {
		return x.Operations
	}
	return nil
}

var File_lit_autopilot_proto protoreflect.FileDescriptor

const file_lit_autopilot_proto_rawDesc = "" +
	"\n" +
	"\x13lit-autopilot.proto\x12\x06litrpc\x1a\x12lit-sessions.proto\"\xbd\x04\n" +
	"\x1aAddAutopilotSessionRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12<\n" +
	"\x18expiry_timestamp_seconds\x18\x02 \x01(\x04B\x020\x01R\x16expiryTimestampSeconds\x12.\n" +
	"\x13mailbox_server_addr\x18\x03 \x01(\tR\x11mailboxServerAddr\x12\x1d\n" +
	"\n" +
	"dev_server\x18\x04 \x01(\bR\tdevServer\x12L\n" +
	"\bfeatures\x18\x05 \x03(\v20.litrpc.AddAutopilotSessionRequest.FeaturesEntryR\bfeatures\x125\n" +
	"\rsession_rules\x18\x06 \x01(\v2\x10.litrpc.RulesMapR\fsessionRules\x12*\n" +
	"\x11no_privacy_mapper\x18\a \x01(\bR\x0fnoPrivacyMapper\x12&\n" +
	"\x0flinked_group_id\x18\b \x01(\fR\rlinkedGroupId\x12#\n" +
	"\rprivacy_flags\x18\t \x01(\x04R\fprivacyFlags\x12*\n" +
	"\x11privacy_flags_set\x18\n" +
	" \x01(\bR\x0fprivacyFlagsSet\x1aR\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.litrpc.FeatureConfigR\x05value:\x028\x01\"O\n" +
	"\rFeatureConfig\x12&\n" +
	"\x05rules\x18\x01 \x01(\v2\x10.litrpc.RulesMapR\x05rules\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\"\x1e\n" +
	"\x1cListAutopilotSessionsRequest\"L\n" +
	"\x1dListAutopilotSessionsResponse\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.litrpc.SessionR\bsessions\"H\n" +
	"\x1bAddAutopilotSessionResponse\x12)\n" +
	"\asession\x18\x01 \x01(\v2\x0f.litrpc.SessionR\asession\"\x1e\n" +
	"\x1cListAutopilotFeaturesRequest\"\xbe\x01\n" +
	"\x1dListAutopilotFeaturesResponse\x12O\n" +
	"\bfeatures\x18\x01 \x03(\v23.litrpc.ListAutopilotFeaturesResponse.FeaturesEntryR\bfeatures\x1aL\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.litrpc.FeatureR\x05value:\x028\x01\"I\n" +
	"\x1dRevokeAutopilotSessionRequest\x12(\n" +
	"\x10local_public_key\x18\x01 \x01(\fR\x0elocalPublicKey\" \n" +
	"\x1eRevokeAutopilotSessionResponse\"\xf6\x02\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x120\n" +
	"\x05rules\x18\x03 \x03(\v2\x1a.litrpc.Feature.RulesEntryR\x05rules\x12>\n" +
	"\x10permissions_list\x18\x04 \x03(\v2\x13.litrpc.PermissionsR\x0fpermissionsList\x12)\n" +
	"\x10requires_upgrade\x18\x05 \x01(\bR\x0frequiresUpgrade\x12%\n" +
	"\x0edefault_config\x18\x06 \x01(\tR\rdefaultConfig\x12#\n" +
	"\rprivacy_flags\x18\a \x01(\x04R\fprivacyFlags\x1aL\n" +
	"\n" +
	"RulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.litrpc.RuleValuesR\x05value:\x028\x01\"\xb1\x01\n" +
	"\n" +
	"RuleValues\x12\x14\n" +
	"\x05known\x18\x01 \x01(\bR\x05known\x12-\n" +
	"\bdefaults\x18\x02 \x01(\v2\x11.litrpc.RuleValueR\bdefaults\x12.\n" +
	"\tmin_value\x18\x03 \x01(\v2\x11.litrpc.RuleValueR\bminValue\x12.\n" +
	"\tmax_value\x18\x04 \x01(\v2\x11.litrpc.RuleValueR\bmaxValue\"a\n" +
	"\vPermissions\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12:\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x1a.litrpc.MacaroonPermissionR\n" +
	"operations2\xa0\x03\n" +
	"\tAutopilot\x12d\n" +
	"\x15ListAutopilotFeatures\x12$.litrpc.ListAutopilotFeaturesRequest\x1a%.litrpc.ListAutopilotFeaturesResponse\x12^\n" +
	"\x13AddAutopilotSession\x12\".litrpc.AddAutopilotSessionRequest\x1a#.litrpc.AddAutopilotSessionResponse\x12d\n" +
	"\x15ListAutopilotSessions\x12$.litrpc.ListAutopilotSessionsRequest\x1a%.litrpc.ListAutopilotSessionsResponse\x12g\n" +
	"\x16RevokeAutopilotSession\x12%.litrpc.RevokeAutopilotSessionRequest\x1a&.litrpc.RevokeAutopilotSessionResponseB4Z2github.com/lightninglabs/lightning-terminal/litrpcb\x06proto3"

var (
	file_lit_autopilot_proto_rawDescOnce sync.Once
	file_lit_autopilot_proto_rawDescData []byte
)

func file_lit_autopilot_proto_rawDescGZIP() []byte {
	file_lit_autopilot_proto_rawDescOnce.Do(func() {
		file_lit_autopilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lit_autopilot_proto_rawDesc), len(file_lit_autopilot_proto_rawDesc)))
	})
	return file_lit_autopilot_proto_rawDescData
}

var file_lit_autopilot_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_lit_autopilot_proto_goTypes = []any{
	(*AddAutopilotSessionRequest)(nil),     // 0: litrpc.AddAutopilotSessionRequest
	(*FeatureConfig)(nil),                  // 1: litrpc.FeatureConfig
	(*ListAutopilotSessionsRequest)(nil),   // 2: litrpc.ListAutopilotSessionsRequest
	(*ListAutopilotSessionsResponse)(nil),  // 3: litrpc.ListAutopilotSessionsResponse
	(*AddAutopilotSessionResponse)(nil),    // 4: litrpc.AddAutopilotSessionResponse
	(*ListAutopilotFeaturesRequest)(nil),   // 5: litrpc.ListAutopilotFeaturesRequest
	(*ListAutopilotFeaturesResponse)(nil),  // 6: litrpc.ListAutopilotFeaturesResponse
	(*RevokeAutopilotSessionRequest)(nil),  // 7: litrpc.RevokeAutopilotSessionRequest
	(*RevokeAutopilotSessionResponse)(nil), // 8: litrpc.RevokeAutopilotSessionResponse
	(*Feature)(nil),                        // 9: litrpc.Feature
	(*RuleValues)(nil),                     // 10: litrpc.RuleValues
	(*Permissions)(nil),                    // 11: litrpc.Permissions
	nil,                                    // 12: litrpc.AddAutopilotSessionRequest.FeaturesEntry
	nil,                                    // 13: litrpc.ListAutopilotFeaturesResponse.FeaturesEntry
	nil,                                    // 14: litrpc.Feature.RulesEntry
	(*RulesMap)(nil),                       // 15: litrpc.RulesMap
	(*Session)(nil),                        // 16: litrpc.Session
	(*RuleValue)(nil),                      // 17: litrpc.RuleValue
	(*MacaroonPermission)(nil),             // 18: litrpc.MacaroonPermission
}
var file_lit_autopilot_proto_depIdxs = []int32{
	12, // 0: litrpc.AddAutopilotSessionRequest.features:type_name -> litrpc.AddAutopilotSessionRequest.FeaturesEntry
	15, // 1: litrpc.AddAutopilotSessionRequest.session_rules:type_name -> litrpc.RulesMap
	15, // 2: litrpc.FeatureConfig.rules:type_name -> litrpc.RulesMap
	16, // 3: litrpc.ListAutopilotSessionsResponse.sessions:type_name -> litrpc.Session
	16, // 4: litrpc.AddAutopilotSessionResponse.session:type_name -> litrpc.Session
	13, // 5: litrpc.ListAutopilotFeaturesResponse.features:type_name -> litrpc.ListAutopilotFeaturesResponse.FeaturesEntry
	14, // 6: litrpc.Feature.rules:type_name -> litrpc.Feature.RulesEntry
	11, // 7: litrpc.Feature.permissions_list:type_name -> litrpc.Permissions
	17, // 8: litrpc.RuleValues.defaults:type_name -> litrpc.RuleValue
	17, // 9: litrpc.RuleValues.min_value:type_name -> litrpc.RuleValue
	17, // 10: litrpc.RuleValues.max_value:type_name -> litrpc.RuleValue
	18, // 11: litrpc.Permissions.operations:type_name -> litrpc.MacaroonPermission
	1,  // 12: litrpc.AddAutopilotSessionRequest.FeaturesEntry.value:type_name -> litrpc.FeatureConfig
	9,  // 13: litrpc.ListAutopilotFeaturesResponse.FeaturesEntry.value:type_name -> litrpc.Feature
	10, // 14: litrpc.Feature.RulesEntry.value:type_name -> litrpc.RuleValues
	5,  // 15: litrpc.Autopilot.ListAutopilotFeatures:input_type -> litrpc.ListAutopilotFeaturesRequest
	0,  // 16: litrpc.Autopilot.AddAutopilotSession:input_type -> litrpc.AddAutopilotSessionRequest
	2,  // 17: litrpc.Autopilot.ListAutopilotSessions:input_type -> litrpc.ListAutopilotSessionsRequest
	7,  // 18: litrpc.Autopilot.RevokeAutopilotSession:input_type -> litrpc.RevokeAutopilotSessionRequest
	6,  // 19: litrpc.Autopilot.ListAutopilotFeatures:output_type -> litrpc.ListAutopilotFeaturesResponse
	4,  // 20: litrpc.Autopilot.AddAutopilotSession:output_type -> litrpc.AddAutopilotSessionResponse
	3,  // 21: litrpc.Autopilot.ListAutopilotSessions:output_type -> litrpc.ListAutopilotSessionsResponse
	8,  // 22: litrpc.Autopilot.RevokeAutopilotSession:output_type -> litrpc.RevokeAutopilotSessionResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_lit_autopilot_proto_init() }
func file_lit_autopilot_proto_init() {
	if File_lit_autopilot_proto != nil {
		return
	}
	file_lit_sessions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lit_autopilot_proto_rawDesc), len(file_lit_autopilot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lit_autopilot_proto_goTypes,
		DependencyIndexes: file_lit_autopilot_proto_depIdxs,
		MessageInfos:      file_lit_autopilot_proto_msgTypes,
	}.Build()
	File_lit_autopilot_proto = out.File
	file_lit_autopilot_proto_goTypes = nil
	file_lit_autopilot_proto_depIdxs = nil
}
