// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: lit-accounts.proto

package litrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The initial account balance in satoshis representing the maximum amount that
	// can be spent.
	AccountBalance uint64 `protobuf:"varint,1,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	// The expiration date of the account as a timestamp. Set to 0 to never expire.
	ExpirationDate int64 `protobuf:"varint,2,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	// An optional label to identify the account. If the label is not empty, then
	// it must be unique, otherwise it couldn't be used to query a single account.
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_lit_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetAccountBalance() uint64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

func (x *CreateAccountRequest) GetExpirationDate() int64 {
	if x != nil {
		return x.ExpirationDate
	}
	return 0
}

func (x *CreateAccountRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type CreateAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new account that was created.
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The macaroon with all permissions required to access the account.
	Macaroon      []byte `protobuf:"bytes,2,opt,name=macaroon,proto3" json:"macaroon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_lit_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CreateAccountResponse) GetMacaroon() []byte {
	if x != nil {
		return x.Macaroon
	}
	return nil
}

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The initial balance in satoshis that was set when the account was created.
	InitialBalance uint64 `protobuf:"varint,2,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	// The current balance in satoshis.
	CurrentBalance int64 `protobuf:"varint,3,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	// Timestamp of the last time the account was updated.
	LastUpdate int64 `protobuf:"varint,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	// Timestamp of the account's expiration date. Zero means it does not expire.
	ExpirationDate int64 `protobuf:"varint,5,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	// The list of invoices created by the account. An invoice created by an
	// account will credit the account balance if it is settled.
	Invoices []*AccountInvoice `protobuf:"bytes,6,rep,name=invoices,proto3" json:"invoices,omitempty"`
	// The list of payments made by the account. A payment made by an account will
	// debit the account balance if it is settled.
	Payments []*AccountPayment `protobuf:"bytes,7,rep,name=payments,proto3" json:"payments,omitempty"`
	// An optional label to identify the account. If this is not empty, then it is
	// guaranteed to be unique.
	Label         string `protobuf:"bytes,8,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_lit_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetInitialBalance() uint64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *Account) GetCurrentBalance() int64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *Account) GetLastUpdate() int64 {
	if x != nil {
		return x.LastUpdate
	}
	return 0
}

func (x *Account) GetExpirationDate() int64 {
	if x != nil {
		return x.ExpirationDate
	}
	return 0
}

func (x *Account) GetInvoices() []*AccountInvoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *Account) GetPayments() []*AccountPayment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *Account) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type AccountInvoice struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment hash of the invoice.
	Hash          []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInvoice) Reset() {
	*x = AccountInvoice{}
	mi := &file_lit_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInvoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInvoice) ProtoMessage() {}

func (x *AccountInvoice) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInvoice.ProtoReflect.Descriptor instead.
func (*AccountInvoice) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *AccountInvoice) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type AccountPayment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payment hash.
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// The state of the payment as reported by lnd.
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// The full amount in satoshis reserved for this payment. This includes the
	// routing fee estimated by the fee limit of the payment request. The actual
	// debited amount will likely be lower if the fee is below the limit.
	FullAmount    int64 `protobuf:"varint,3,opt,name=full_amount,json=fullAmount,proto3" json:"full_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountPayment) Reset() {
	*x = AccountPayment{}
	mi := &file_lit_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPayment) ProtoMessage() {}

func (x *AccountPayment) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPayment.ProtoReflect.Descriptor instead.
func (*AccountPayment) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *AccountPayment) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *AccountPayment) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AccountPayment) GetFullAmount() int64 {
	if x != nil {
		return x.FullAmount
	}
	return 0
}

type UpdateAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the account to update. Either the ID or the label must be set.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Deprecated, use the `litcli update credit` or `litcli update debit`
	// commands instead. The new account balance to set. Set to -1 to not
	// update the balance.
	//
	// Deprecated: Marked as deprecated in lit-accounts.proto.
	AccountBalance int64 `protobuf:"varint,2,opt,name=account_balance,json=accountBalance,proto3" json:"account_balance,omitempty"`
	// The new account expiry to set. Set to -1 to not update the expiry. Set to 0
	// to never expire.
	ExpirationDate int64 `protobuf:"varint,3,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	// The label of the account to update. If an account has no label, then the ID
	// must be used instead. This field is only used to identify the account.
	Label string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	// The new label to set for the account.
	NewLabel      string `protobuf:"bytes,5,opt,name=new_label,json=newLabel,proto3" json:"new_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_lit_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Deprecated: Marked as deprecated in lit-accounts.proto.
func (x *UpdateAccountRequest) GetAccountBalance() int64 {
	if x != nil {
		return x.AccountBalance
	}
	return 0
}

func (x *UpdateAccountRequest) GetExpirationDate() int64 {
	if x != nil {
		return x.ExpirationDate
	}
	return 0
}

func (x *UpdateAccountRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateAccountRequest) GetNewLabel() string {
	if x != nil {
		return x.NewLabel
	}
	return ""
}

type CreditAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the account to credit.
	Account *AccountIdentifier `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The amount by which the account's balance should be credited.
	Amount        uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditAccountRequest) Reset() {
	*x = CreditAccountRequest{}
	mi := &file_lit_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountRequest) ProtoMessage() {}

func (x *CreditAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountRequest.ProtoReflect.Descriptor instead.
func (*CreditAccountRequest) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *CreditAccountRequest) GetAccount() *AccountIdentifier {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *CreditAccountRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreditAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The credited account.
	Account       *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditAccountResponse) Reset() {
	*x = CreditAccountResponse{}
	mi := &file_lit_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountResponse) ProtoMessage() {}

func (x *CreditAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountResponse.ProtoReflect.Descriptor instead.
func (*CreditAccountResponse) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *CreditAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type DebitAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The identifier of the account to debit.
	Account *AccountIdentifier `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The amount by which the account's balance should be debited.
	Amount        uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitAccountRequest) Reset() {
	*x = DebitAccountRequest{}
	mi := &file_lit_accounts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitAccountRequest) ProtoMessage() {}

func (x *DebitAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitAccountRequest.ProtoReflect.Descriptor instead.
func (*DebitAccountRequest) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *DebitAccountRequest) GetAccount() *AccountIdentifier {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *DebitAccountRequest) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DebitAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The debited account.
	Account       *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitAccountResponse) Reset() {
	*x = DebitAccountResponse{}
	mi := &file_lit_accounts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitAccountResponse) ProtoMessage() {}

func (x *DebitAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitAccountResponse.ProtoReflect.Descriptor instead.
func (*DebitAccountResponse) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *DebitAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_lit_accounts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{10}
}

type ListAccountsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All accounts in the account database.
	Accounts      []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_lit_accounts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type AccountInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hexadecimal ID of the account to remove. Either the ID or the label must
	// be set.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The label of the account to remove. If an account has no label, then the ID
	// must be used instead.
	Label         string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountInfoRequest) Reset() {
	*x = AccountInfoRequest{}
	mi := &file_lit_accounts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoRequest) ProtoMessage() {}

func (x *AccountInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoRequest.ProtoReflect.Descriptor instead.
func (*AccountInfoRequest) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{12}
}

func (x *AccountInfoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountInfoRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RemoveAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hexadecimal ID of the account to remove. Either the ID or the label must
	// be set.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The label of the account to remove. If an account has no label, then the ID
	// must be used instead.
	Label         string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAccountRequest) Reset() {
	*x = RemoveAccountRequest{}
	mi := &file_lit_accounts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAccountRequest) ProtoMessage() {}

func (x *RemoveAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAccountRequest.ProtoReflect.Descriptor instead.
func (*RemoveAccountRequest) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RemoveAccountRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type RemoveAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAccountResponse) Reset() {
	*x = RemoveAccountResponse{}
	mi := &file_lit_accounts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAccountResponse) ProtoMessage() {}

func (x *RemoveAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAccountResponse.ProtoReflect.Descriptor instead.
func (*RemoveAccountResponse) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{14}
}

type AccountIdentifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*AccountIdentifier_Id
	//	*AccountIdentifier_Label
	Identifier    isAccountIdentifier_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountIdentifier) Reset() {
	*x = AccountIdentifier{}
	mi := &file_lit_accounts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountIdentifier) ProtoMessage() {}

func (x *AccountIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_lit_accounts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountIdentifier.ProtoReflect.Descriptor instead.
func (*AccountIdentifier) Descriptor() ([]byte, []int) {
	return file_lit_accounts_proto_rawDescGZIP(), []int{15}
}

func (x *AccountIdentifier) GetIdentifier() isAccountIdentifier_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *AccountIdentifier) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*AccountIdentifier_Id); ok {
			return x.Id
		}
	}
	return ""
}

func (x *AccountIdentifier) GetLabel() string {
	if x != nil {
		if x, ok := x.Identifier.(*AccountIdentifier_Label); ok {
			return x.Label
		}
	}
	return ""
}

type isAccountIdentifier_Identifier interface {
	isAccountIdentifier_Identifier()
}

type AccountIdentifier_Id struct {
	// The ID of the account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3,oneof"`
}

type AccountIdentifier_Label struct {
	// The label of the account.
	Label string `protobuf:"bytes,2,opt,name=label,proto3,oneof"`
}

func (*AccountIdentifier_Id) isAccountIdentifier_Identifier() {}

func (*AccountIdentifier_Label) isAccountIdentifier_Identifier() {}

var File_lit_accounts_proto protoreflect.FileDescriptor

const file_lit_accounts_proto_rawDesc = "" +
	"\n" +
	"\x12lit-accounts.proto\x12\x06litrpc\"~\n" +
	"\x14CreateAccountRequest\x12'\n" +
	"\x0faccount_balance\x18\x01 \x01(\x04R\x0eaccountBalance\x12'\n" +
	"\x0fexpiration_date\x18\x02 \x01(\x03R\x0eexpirationDate\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"^\n" +
	"\x15CreateAccountResponse\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.litrpc.AccountR\aaccount\x12\x1a\n" +
	"\bmacaroon\x18\x02 \x01(\fR\bmacaroon\"\xb3\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0finitial_balance\x18\x02 \x01(\x04R\x0einitialBalance\x12'\n" +
	"\x0fcurrent_balance\x18\x03 \x01(\x03R\x0ecurrentBalance\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\x03R\n" +
	"lastUpdate\x12'\n" +
	"\x0fexpiration_date\x18\x05 \x01(\x03R\x0eexpirationDate\x122\n" +
	"\binvoices\x18\x06 \x03(\v2\x16.litrpc.AccountInvoiceR\binvoices\x122\n" +
	"\bpayments\x18\a \x03(\v2\x16.litrpc.AccountPaymentR\bpayments\x12\x14\n" +
	"\x05label\x18\b \x01(\tR\x05label\"$\n" +
	"\x0eAccountInvoice\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\"[\n" +
	"\x0eAccountPayment\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vfull_amount\x18\x03 \x01(\x03R\n" +
	"fullAmount\"\xaf\x01\n" +
	"\x14UpdateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x0faccount_balance\x18\x02 \x01(\x03B\x02\x18\x01R\x0eaccountBalance\x12'\n" +
	"\x0fexpiration_date\x18\x03 \x01(\x03R\x0eexpirationDate\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\x12\x1b\n" +
	"\tnew_label\x18\x05 \x01(\tR\bnewLabel\"c\n" +
	"\x14CreditAccountRequest\x123\n" +
	"\aaccount\x18\x01 \x01(\v2\x19.litrpc.AccountIdentifierR\aaccount\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\"B\n" +
	"\x15CreditAccountResponse\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.litrpc.AccountR\aaccount\"b\n" +
	"\x13DebitAccountRequest\x123\n" +
	"\aaccount\x18\x01 \x01(\v2\x19.litrpc.AccountIdentifierR\aaccount\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"A\n" +
	"\x14DebitAccountResponse\x12)\n" +
	"\aaccount\x18\x01 \x01(\v2\x0f.litrpc.AccountR\aaccount\"\x15\n" +
	"\x13ListAccountsRequest\"C\n" +
	"\x14ListAccountsResponse\x12+\n" +
	"\baccounts\x18\x01 \x03(\v2\x0f.litrpc.AccountR\baccounts\":\n" +
	"\x12AccountInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"<\n" +
	"\x14RemoveAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x17\n" +
	"\x15RemoveAccountResponse\"K\n" +
	"\x11AccountIdentifier\x12\x10\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x12\x16\n" +
	"\x05label\x18\x02 \x01(\tH\x00R\x05labelB\f\n" +
	"\n" +
	"identifier2\x86\x04\n" +
	"\bAccounts\x12L\n" +
	"\rCreateAccount\x12\x1c.litrpc.CreateAccountRequest\x1a\x1d.litrpc.CreateAccountResponse\x12>\n" +
	"\rUpdateAccount\x12\x1c.litrpc.UpdateAccountRequest\x1a\x0f.litrpc.Account\x12L\n" +
	"\rCreditAccount\x12\x1c.litrpc.CreditAccountRequest\x1a\x1d.litrpc.CreditAccountResponse\x12I\n" +
	"\fDebitAccount\x12\x1b.litrpc.DebitAccountRequest\x1a\x1c.litrpc.DebitAccountResponse\x12I\n" +
	"\fListAccounts\x12\x1b.litrpc.ListAccountsRequest\x1a\x1c.litrpc.ListAccountsResponse\x12:\n" +
	"\vAccountInfo\x12\x1a.litrpc.AccountInfoRequest\x1a\x0f.litrpc.Account\x12L\n" +
	"\rRemoveAccount\x12\x1c.litrpc.RemoveAccountRequest\x1a\x1d.litrpc.RemoveAccountResponseB4Z2github.com/lightninglabs/lightning-terminal/litrpcb\x06proto3"

var (
	file_lit_accounts_proto_rawDescOnce sync.Once
	file_lit_accounts_proto_rawDescData []byte
)

func file_lit_accounts_proto_rawDescGZIP() []byte {
	file_lit_accounts_proto_rawDescOnce.Do(func() {
		file_lit_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lit_accounts_proto_rawDesc), len(file_lit_accounts_proto_rawDesc)))
	})
	return file_lit_accounts_proto_rawDescData
}

var file_lit_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_lit_accounts_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: litrpc.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: litrpc.CreateAccountResponse
	(*Account)(nil),               // 2: litrpc.Account
	(*AccountInvoice)(nil),        // 3: litrpc.AccountInvoice
	(*AccountPayment)(nil),        // 4: litrpc.AccountPayment
	(*UpdateAccountRequest)(nil),  // 5: litrpc.UpdateAccountRequest
	(*CreditAccountRequest)(nil),  // 6: litrpc.CreditAccountRequest
	(*CreditAccountResponse)(nil), // 7: litrpc.CreditAccountResponse
	(*DebitAccountRequest)(nil),   // 8: litrpc.DebitAccountRequest
	(*DebitAccountResponse)(nil),  // 9: litrpc.DebitAccountResponse
	(*ListAccountsRequest)(nil),   // 10: litrpc.ListAccountsRequest
	(*ListAccountsResponse)(nil),  // 11: litrpc.ListAccountsResponse
	(*AccountInfoRequest)(nil),    // 12: litrpc.AccountInfoRequest
	(*RemoveAccountRequest)(nil),  // 13: litrpc.RemoveAccountRequest
	(*RemoveAccountResponse)(nil), // 14: litrpc.RemoveAccountResponse
	(*AccountIdentifier)(nil),     // 15: litrpc.AccountIdentifier
}
var file_lit_accounts_proto_depIdxs = []int32{
	2,  // 0: litrpc.CreateAccountResponse.account:type_name -> litrpc.Account
	3,  // 1: litrpc.Account.invoices:type_name -> litrpc.AccountInvoice
	4,  // 2: litrpc.Account.payments:type_name -> litrpc.AccountPayment
	15, // 3: litrpc.CreditAccountRequest.account:type_name -> litrpc.AccountIdentifier
	2,  // 4: litrpc.CreditAccountResponse.account:type_name -> litrpc.Account
	15, // 5: litrpc.DebitAccountRequest.account:type_name -> litrpc.AccountIdentifier
	2,  // 6: litrpc.DebitAccountResponse.account:type_name -> litrpc.Account
	2,  // 7: litrpc.ListAccountsResponse.accounts:type_name -> litrpc.Account
	0,  // 8: litrpc.Accounts.CreateAccount:input_type -> litrpc.CreateAccountRequest
	5,  // 9: litrpc.Accounts.UpdateAccount:input_type -> litrpc.UpdateAccountRequest
	6,  // 10: litrpc.Accounts.CreditAccount:input_type -> litrpc.CreditAccountRequest
	8,  // 11: litrpc.Accounts.DebitAccount:input_type -> litrpc.DebitAccountRequest
	10, // 12: litrpc.Accounts.ListAccounts:input_type -> litrpc.ListAccountsRequest
	12, // 13: litrpc.Accounts.AccountInfo:input_type -> litrpc.AccountInfoRequest
	13, // 14: litrpc.Accounts.RemoveAccount:input_type -> litrpc.RemoveAccountRequest
	1,  // 15: litrpc.Accounts.CreateAccount:output_type -> litrpc.CreateAccountResponse
	2,  // 16: litrpc.Accounts.UpdateAccount:output_type -> litrpc.Account
	7,  // 17: litrpc.Accounts.CreditAccount:output_type -> litrpc.CreditAccountResponse
	9,  // 18: litrpc.Accounts.DebitAccount:output_type -> litrpc.DebitAccountResponse
	11, // 19: litrpc.Accounts.ListAccounts:output_type -> litrpc.ListAccountsResponse
	2,  // 20: litrpc.Accounts.AccountInfo:output_type -> litrpc.Account
	14, // 21: litrpc.Accounts.RemoveAccount:output_type -> litrpc.RemoveAccountResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_lit_accounts_proto_init() }
func file_lit_accounts_proto_init() {
	if File_lit_accounts_proto != nil {
		return
	}
	file_lit_accounts_proto_msgTypes[15].OneofWrappers = []any{
		(*AccountIdentifier_Id)(nil),
		(*AccountIdentifier_Label)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lit_accounts_proto_rawDesc), len(file_lit_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lit_accounts_proto_goTypes,
		DependencyIndexes: file_lit_accounts_proto_depIdxs,
		MessageInfos:      file_lit_accounts_proto_msgTypes,
	}.Build()
	File_lit_accounts_proto = out.File
	file_lit_accounts_proto_goTypes = nil
	file_lit_accounts_proto_depIdxs = nil
}
