name: "Setup Golang environment"
description: "A reusable workflow that's used to set up the Go environment and cache."
inputs:
  go-version:
    description: "The version of Golang to set up"
    required: true
  key-prefix:
    description: "A prefix to use for the cache key, to separate cache entries from other workflows. When provided, uses a custom cache instead of setup-go's default caching."
    required: false

runs:
  using: "composite"

  steps:
    - name: set git config
      shell: bash
      run: |
        git config --global core.eol lf
        git config --global core.autocrlf false

    - name: setup go ${{ inputs.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: '${{ inputs.go-version }}'
        cache: ${{ inputs.key-prefix == '' }}

    - name: cache go (custom key)
      if: inputs.key-prefix != ''
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: |
          ${{ inputs.key-prefix }}-go-${{ runner.os }}-${{ runner.arch }}-${{ inputs.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ inputs.key-prefix }}-go-${{ runner.os }}-${{ runner.arch }}-${{ inputs.go-version }}-

    - name: set GOPATH
      shell: bash
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
