// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: autopilotserver.proto

package autopilotserverrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TermsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermsRequest) Reset() {
	*x = TermsRequest{}
	mi := &file_autopilotserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsRequest) ProtoMessage() {}

func (x *TermsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsRequest.ProtoReflect.Descriptor instead.
func (*TermsRequest) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{0}
}

type TermsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MinRequiredVersion *Version               `protobuf:"bytes,1,opt,name=min_required_version,json=minRequiredVersion,proto3" json:"min_required_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TermsResponse) Reset() {
	*x = TermsResponse{}
	mi := &file_autopilotserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermsResponse) ProtoMessage() {}

func (x *TermsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermsResponse.ProtoReflect.Descriptor instead.
func (*TermsResponse) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{1}
}

func (x *TermsResponse) GetMinRequiredVersion() *Version {
	if x != nil {
		return x.MinRequiredVersion
	}
	return nil
}

type Version struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The major application version.
	Major uint32 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	// The minor application version.
	Minor uint32 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	// The application patch number.
	Patch         uint32 `protobuf:"varint,3,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_autopilotserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{2}
}

func (x *Version) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Version) GetPatch() uint32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

type ListFeaturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturesRequest) Reset() {
	*x = ListFeaturesRequest{}
	mi := &file_autopilotserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturesRequest) ProtoMessage() {}

func (x *ListFeaturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturesRequest.ProtoReflect.Descriptor instead.
func (*ListFeaturesRequest) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{3}
}

type ActivateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The static public key of the client that is to be used for future noise
	// handshakes. Since the autopilot is the initiator of a connection, the
	// client's key is called the "responder" key.
	ResponderPubKey []byte `protobuf:"bytes,1,opt,name=responder_pub_key,json=responderPubKey,proto3" json:"responder_pub_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivateSessionRequest) Reset() {
	*x = ActivateSessionRequest{}
	mi := &file_autopilotserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateSessionRequest) ProtoMessage() {}

func (x *ActivateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateSessionRequest.ProtoReflect.Descriptor instead.
func (*ActivateSessionRequest) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{4}
}

func (x *ActivateSessionRequest) GetResponderPubKey() []byte {
	if x != nil {
		return x.ResponderPubKey
	}
	return nil
}

type ActivateSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The autopilot's static pub key to be used for the noise connection with the
	// client.
	InitiatorPubKey []byte `protobuf:"bytes,1,opt,name=initiator_pub_key,json=initiatorPubKey,proto3" json:"initiator_pub_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActivateSessionResponse) Reset() {
	*x = ActivateSessionResponse{}
	mi := &file_autopilotserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateSessionResponse) ProtoMessage() {}

func (x *ActivateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateSessionResponse.ProtoReflect.Descriptor instead.
func (*ActivateSessionResponse) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{5}
}

func (x *ActivateSessionResponse) GetInitiatorPubKey() []byte {
	if x != nil {
		return x.InitiatorPubKey
	}
	return nil
}

type ListFeaturesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A map of feature name to Feature object. This map represents each of the
	// features supported by the autopilot server along with the details of
	// each feature.
	Features      map[string]*Feature `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFeaturesResponse) Reset() {
	*x = ListFeaturesResponse{}
	mi := &file_autopilotserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFeaturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFeaturesResponse) ProtoMessage() {}

func (x *ListFeaturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFeaturesResponse.ProtoReflect.Descriptor instead.
func (*ListFeaturesResponse) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{6}
}

func (x *ListFeaturesResponse) GetFeatures() map[string]*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

type Feature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The string identifier of the feature.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A human-readable description of what the feature offers.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// A map of the rule names to rule values that make sense for this feature.
	Rules map[string]*Rule `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A list of the permissions that the feature will require to operate.
	PermissionsList []*Permissions `protobuf:"bytes,4,rep,name=permissions_list,json=permissionsList,proto3" json:"permissions_list,omitempty"`
	// The JSON-marshaled representation of a feature's default configuration.
	DefaultConfig []byte `protobuf:"bytes,5,opt,name=default_config,json=defaultConfig,proto3" json:"default_config,omitempty"`
	// This feature may require relaxed privacy obfuscation that can be enabled
	// with these flags.
	PrivacyFlags  uint64 `protobuf:"varint,6,opt,name=privacy_flags,json=privacyFlags,proto3" json:"privacy_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feature) Reset() {
	*x = Feature{}
	mi := &file_autopilotserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{7}
}

func (x *Feature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Feature) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Feature) GetRules() map[string]*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *Feature) GetPermissionsList() []*Permissions {
	if x != nil {
		return x.PermissionsList
	}
	return nil
}

func (x *Feature) GetDefaultConfig() []byte {
	if x != nil {
		return x.DefaultConfig
	}
	return nil
}

func (x *Feature) GetPrivacyFlags() uint64 {
	if x != nil {
		return x.PrivacyFlags
	}
	return 0
}

type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the rule.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The recommended default values for the rule. These may vary from feature
	// to feature.
	Default []byte `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	// The minimum sane value of the rule that is allowed for the associated
	// feature.
	MinValue []byte `protobuf:"bytes,3,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	// The maximum sane value of the rule that is allowed for the associated
	// feature.
	MaxValue      []byte `protobuf:"bytes,4,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_autopilotserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{8}
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDefault() []byte {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *Rule) GetMinValue() []byte {
	if x != nil {
		return x.MinValue
	}
	return nil
}

func (x *Rule) GetMaxValue() []byte {
	if x != nil {
		return x.MaxValue
	}
	return nil
}

type Permissions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URI of the method that the operation set is referring to.
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// A list of operations that the method can perform
	Operations    []*Operation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permissions) Reset() {
	*x = Permissions{}
	mi := &file_autopilotserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissions) ProtoMessage() {}

func (x *Permissions) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissions.ProtoReflect.Descriptor instead.
func (*Permissions) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{9}
}

func (x *Permissions) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Permissions) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entity to which the action applies.
	Entity string `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	// The action that can be performed on the above specified entity.
	Action        string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_autopilotserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{10}
}

func (x *Operation) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Operation) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type RegisterSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The static public key of the client that is to be used for future noise
	// handshakes. Since the autopilot is the initiator of a connection, the
	// client's key is called the "responder" key.
	ResponderPubKey []byte `protobuf:"bytes,1,opt,name=responder_pub_key,json=responderPubKey,proto3" json:"responder_pub_key,omitempty"`
	// The address of the mailbox that the client will use for the LNC connection.
	MailboxAddr string `protobuf:"bytes,2,opt,name=mailbox_addr,json=mailboxAddr,proto3" json:"mailbox_addr,omitempty"`
	// Set to true if tls should be skipped for when connecting to the mailbox.
	DevServer bool `protobuf:"varint,3,opt,name=dev_server,json=devServer,proto3" json:"dev_server,omitempty"`
	// A map from feature name to configuration bytes for that feature.
	FeatureConfigs map[string][]byte `protobuf:"bytes,4,rep,name=feature_configs,json=featureConfigs,proto3" json:"feature_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The version of the Lit client.
	LitVersion *Version `protobuf:"bytes,5,opt,name=lit_version,json=litVersion,proto3" json:"lit_version,omitempty"`
	// The version of the LND that the Lit client is using.
	LndVersion *Version `protobuf:"bytes,6,opt,name=lnd_version,json=lndVersion,proto3" json:"lnd_version,omitempty"`
	// If set, this is the responder public key of a first session in the group
	// that this new session should be linked to.
	GroupResponderKey []byte `protobuf:"bytes,7,opt,name=group_responder_key,json=groupResponderKey,proto3" json:"group_responder_key,omitempty"`
	// The signature by the first responder key of the serialised new responder
	// key.
	GroupResponderSig []byte `protobuf:"bytes,8,opt,name=group_responder_sig,json=groupResponderSig,proto3" json:"group_responder_sig,omitempty"`
	// The privacy flags used by this session.
	PrivacyFlags  uint64 `protobuf:"varint,9,opt,name=privacy_flags,json=privacyFlags,proto3" json:"privacy_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSessionRequest) Reset() {
	*x = RegisterSessionRequest{}
	mi := &file_autopilotserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSessionRequest) ProtoMessage() {}

func (x *RegisterSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSessionRequest.ProtoReflect.Descriptor instead.
func (*RegisterSessionRequest) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterSessionRequest) GetResponderPubKey() []byte {
	if x != nil {
		return x.ResponderPubKey
	}
	return nil
}

func (x *RegisterSessionRequest) GetMailboxAddr() string {
	if x != nil {
		return x.MailboxAddr
	}
	return ""
}

func (x *RegisterSessionRequest) GetDevServer() bool {
	if x != nil {
		return x.DevServer
	}
	return false
}

func (x *RegisterSessionRequest) GetFeatureConfigs() map[string][]byte {
	if x != nil {
		return x.FeatureConfigs
	}
	return nil
}

func (x *RegisterSessionRequest) GetLitVersion() *Version {
	if x != nil {
		return x.LitVersion
	}
	return nil
}

func (x *RegisterSessionRequest) GetLndVersion() *Version {
	if x != nil {
		return x.LndVersion
	}
	return nil
}

func (x *RegisterSessionRequest) GetGroupResponderKey() []byte {
	if x != nil {
		return x.GroupResponderKey
	}
	return nil
}

func (x *RegisterSessionRequest) GetGroupResponderSig() []byte {
	if x != nil {
		return x.GroupResponderSig
	}
	return nil
}

func (x *RegisterSessionRequest) GetPrivacyFlags() uint64 {
	if x != nil {
		return x.PrivacyFlags
	}
	return 0
}

type RegisterSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The autopilot's static pub key to be used for the noise connection with the
	// client.
	InitiatorPubKey []byte `protobuf:"bytes,1,opt,name=initiator_pub_key,json=initiatorPubKey,proto3" json:"initiator_pub_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterSessionResponse) Reset() {
	*x = RegisterSessionResponse{}
	mi := &file_autopilotserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSessionResponse) ProtoMessage() {}

func (x *RegisterSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSessionResponse.ProtoReflect.Descriptor instead.
func (*RegisterSessionResponse) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterSessionResponse) GetInitiatorPubKey() []byte {
	if x != nil {
		return x.InitiatorPubKey
	}
	return nil
}

type RevokeSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The client's key for the session that the client is revoking.
	ResponderPubKey []byte `protobuf:"bytes,1,opt,name=responder_pub_key,json=responderPubKey,proto3" json:"responder_pub_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_autopilotserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeSessionRequest) GetResponderPubKey() []byte {
	if x != nil {
		return x.ResponderPubKey
	}
	return nil
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_autopilotserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autopilotserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_autopilotserver_proto_rawDescGZIP(), []int{14}
}

var File_autopilotserver_proto protoreflect.FileDescriptor

const file_autopilotserver_proto_rawDesc = "" +
	"\n" +
	"\x15autopilotserver.proto\x12\x12autopilotserverrpc\"\x0e\n" +
	"\fTermsRequest\"^\n" +
	"\rTermsResponse\x12M\n" +
	"\x14min_required_version\x18\x01 \x01(\v2\x1b.autopilotserverrpc.VersionR\x12minRequiredVersion\"K\n" +
	"\aVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12\x14\n" +
	"\x05patch\x18\x03 \x01(\rR\x05patch\"\x15\n" +
	"\x13ListFeaturesRequest\"D\n" +
	"\x16ActivateSessionRequest\x12*\n" +
	"\x11responder_pub_key\x18\x01 \x01(\fR\x0fresponderPubKey\"E\n" +
	"\x17ActivateSessionResponse\x12*\n" +
	"\x11initiator_pub_key\x18\x01 \x01(\fR\x0finitiatorPubKey\"\xc4\x01\n" +
	"\x14ListFeaturesResponse\x12R\n" +
	"\bfeatures\x18\x01 \x03(\v26.autopilotserverrpc.ListFeaturesResponse.FeaturesEntryR\bfeatures\x1aX\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.autopilotserverrpc.FeatureR\x05value:\x028\x01\"\xe9\x02\n" +
	"\aFeature\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12<\n" +
	"\x05rules\x18\x03 \x03(\v2&.autopilotserverrpc.Feature.RulesEntryR\x05rules\x12J\n" +
	"\x10permissions_list\x18\x04 \x03(\v2\x1f.autopilotserverrpc.PermissionsR\x0fpermissionsList\x12%\n" +
	"\x0edefault_config\x18\x05 \x01(\fR\rdefaultConfig\x12#\n" +
	"\rprivacy_flags\x18\x06 \x01(\x04R\fprivacyFlags\x1aR\n" +
	"\n" +
	"RulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.autopilotserverrpc.RuleR\x05value:\x028\x01\"n\n" +
	"\x04Rule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adefault\x18\x02 \x01(\fR\adefault\x12\x1b\n" +
	"\tmin_value\x18\x03 \x01(\fR\bminValue\x12\x1b\n" +
	"\tmax_value\x18\x04 \x01(\fR\bmaxValue\"d\n" +
	"\vPermissions\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12=\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x1d.autopilotserverrpc.OperationR\n" +
	"operations\";\n" +
	"\tOperation\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xb3\x04\n" +
	"\x16RegisterSessionRequest\x12*\n" +
	"\x11responder_pub_key\x18\x01 \x01(\fR\x0fresponderPubKey\x12!\n" +
	"\fmailbox_addr\x18\x02 \x01(\tR\vmailboxAddr\x12\x1d\n" +
	"\n" +
	"dev_server\x18\x03 \x01(\bR\tdevServer\x12g\n" +
	"\x0ffeature_configs\x18\x04 \x03(\v2>.autopilotserverrpc.RegisterSessionRequest.FeatureConfigsEntryR\x0efeatureConfigs\x12<\n" +
	"\vlit_version\x18\x05 \x01(\v2\x1b.autopilotserverrpc.VersionR\n" +
	"litVersion\x12<\n" +
	"\vlnd_version\x18\x06 \x01(\v2\x1b.autopilotserverrpc.VersionR\n" +
	"lndVersion\x12.\n" +
	"\x13group_responder_key\x18\a \x01(\fR\x11groupResponderKey\x12.\n" +
	"\x13group_responder_sig\x18\b \x01(\fR\x11groupResponderSig\x12#\n" +
	"\rprivacy_flags\x18\t \x01(\x04R\fprivacyFlags\x1aA\n" +
	"\x13FeatureConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"E\n" +
	"\x17RegisterSessionResponse\x12*\n" +
	"\x11initiator_pub_key\x18\x01 \x01(\fR\x0finitiatorPubKey\"B\n" +
	"\x14RevokeSessionRequest\x12*\n" +
	"\x11responder_pub_key\x18\x01 \x01(\fR\x0fresponderPubKey\"\x17\n" +
	"\x15RevokeSessionResponse2\xfa\x03\n" +
	"\tAutopilot\x12L\n" +
	"\x05Terms\x12 .autopilotserverrpc.TermsRequest\x1a!.autopilotserverrpc.TermsResponse\x12a\n" +
	"\fListFeatures\x12'.autopilotserverrpc.ListFeaturesRequest\x1a(.autopilotserverrpc.ListFeaturesResponse\x12j\n" +
	"\x0fRegisterSession\x12*.autopilotserverrpc.RegisterSessionRequest\x1a+.autopilotserverrpc.RegisterSessionResponse\x12j\n" +
	"\x0fActivateSession\x12*.autopilotserverrpc.ActivateSessionRequest\x1a+.autopilotserverrpc.ActivateSessionResponse\x12d\n" +
	"\rRevokeSession\x12(.autopilotserverrpc.RevokeSessionRequest\x1a).autopilotserverrpc.RevokeSessionResponseB@Z>github.com/lightninglabs/lightning-terminal/autopilotserverrpcb\x06proto3"

var (
	file_autopilotserver_proto_rawDescOnce sync.Once
	file_autopilotserver_proto_rawDescData []byte
)

func file_autopilotserver_proto_rawDescGZIP() []byte {
	file_autopilotserver_proto_rawDescOnce.Do(func() {
		file_autopilotserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autopilotserver_proto_rawDesc), len(file_autopilotserver_proto_rawDesc)))
	})
	return file_autopilotserver_proto_rawDescData
}

var file_autopilotserver_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_autopilotserver_proto_goTypes = []any{
	(*TermsRequest)(nil),            // 0: autopilotserverrpc.TermsRequest
	(*TermsResponse)(nil),           // 1: autopilotserverrpc.TermsResponse
	(*Version)(nil),                 // 2: autopilotserverrpc.Version
	(*ListFeaturesRequest)(nil),     // 3: autopilotserverrpc.ListFeaturesRequest
	(*ActivateSessionRequest)(nil),  // 4: autopilotserverrpc.ActivateSessionRequest
	(*ActivateSessionResponse)(nil), // 5: autopilotserverrpc.ActivateSessionResponse
	(*ListFeaturesResponse)(nil),    // 6: autopilotserverrpc.ListFeaturesResponse
	(*Feature)(nil),                 // 7: autopilotserverrpc.Feature
	(*Rule)(nil),                    // 8: autopilotserverrpc.Rule
	(*Permissions)(nil),             // 9: autopilotserverrpc.Permissions
	(*Operation)(nil),               // 10: autopilotserverrpc.Operation
	(*RegisterSessionRequest)(nil),  // 11: autopilotserverrpc.RegisterSessionRequest
	(*RegisterSessionResponse)(nil), // 12: autopilotserverrpc.RegisterSessionResponse
	(*RevokeSessionRequest)(nil),    // 13: autopilotserverrpc.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),   // 14: autopilotserverrpc.RevokeSessionResponse
	nil,                             // 15: autopilotserverrpc.ListFeaturesResponse.FeaturesEntry
	nil,                             // 16: autopilotserverrpc.Feature.RulesEntry
	nil,                             // 17: autopilotserverrpc.RegisterSessionRequest.FeatureConfigsEntry
}
var file_autopilotserver_proto_depIdxs = []int32{
	2,  // 0: autopilotserverrpc.TermsResponse.min_required_version:type_name -> autopilotserverrpc.Version
	15, // 1: autopilotserverrpc.ListFeaturesResponse.features:type_name -> autopilotserverrpc.ListFeaturesResponse.FeaturesEntry
	16, // 2: autopilotserverrpc.Feature.rules:type_name -> autopilotserverrpc.Feature.RulesEntry
	9,  // 3: autopilotserverrpc.Feature.permissions_list:type_name -> autopilotserverrpc.Permissions
	10, // 4: autopilotserverrpc.Permissions.operations:type_name -> autopilotserverrpc.Operation
	17, // 5: autopilotserverrpc.RegisterSessionRequest.feature_configs:type_name -> autopilotserverrpc.RegisterSessionRequest.FeatureConfigsEntry
	2,  // 6: autopilotserverrpc.RegisterSessionRequest.lit_version:type_name -> autopilotserverrpc.Version
	2,  // 7: autopilotserverrpc.RegisterSessionRequest.lnd_version:type_name -> autopilotserverrpc.Version
	7,  // 8: autopilotserverrpc.ListFeaturesResponse.FeaturesEntry.value:type_name -> autopilotserverrpc.Feature
	8,  // 9: autopilotserverrpc.Feature.RulesEntry.value:type_name -> autopilotserverrpc.Rule
	0,  // 10: autopilotserverrpc.Autopilot.Terms:input_type -> autopilotserverrpc.TermsRequest
	3,  // 11: autopilotserverrpc.Autopilot.ListFeatures:input_type -> autopilotserverrpc.ListFeaturesRequest
	11, // 12: autopilotserverrpc.Autopilot.RegisterSession:input_type -> autopilotserverrpc.RegisterSessionRequest
	4,  // 13: autopilotserverrpc.Autopilot.ActivateSession:input_type -> autopilotserverrpc.ActivateSessionRequest
	13, // 14: autopilotserverrpc.Autopilot.RevokeSession:input_type -> autopilotserverrpc.RevokeSessionRequest
	1,  // 15: autopilotserverrpc.Autopilot.Terms:output_type -> autopilotserverrpc.TermsResponse
	6,  // 16: autopilotserverrpc.Autopilot.ListFeatures:output_type -> autopilotserverrpc.ListFeaturesResponse
	12, // 17: autopilotserverrpc.Autopilot.RegisterSession:output_type -> autopilotserverrpc.RegisterSessionResponse
	5,  // 18: autopilotserverrpc.Autopilot.ActivateSession:output_type -> autopilotserverrpc.ActivateSessionResponse
	14, // 19: autopilotserverrpc.Autopilot.RevokeSession:output_type -> autopilotserverrpc.RevokeSessionResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_autopilotserver_proto_init() }
func file_autopilotserver_proto_init() {
	if File_autopilotserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autopilotserver_proto_rawDesc), len(file_autopilotserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_autopilotserver_proto_goTypes,
		DependencyIndexes: file_autopilotserver_proto_depIdxs,
		MessageInfos:      file_autopilotserver_proto_msgTypes,
	}.Build()
	File_autopilotserver_proto = out.File
	file_autopilotserver_proto_goTypes = nil
	file_autopilotserver_proto_depIdxs = nil
}
